version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      vite-ecosystem:
        patterns:
          - "vite"
          - "@vitejs/*"
          - "@preact/*"
      preact:
        patterns:
          - "preact"
      typescript-ecosystem:
        patterns:
          - "typescript"
          - "typescript-eslint"
          - "@typescript-eslint/*"
      eslint:
        patterns:
          - "eslint"
          - "eslint-*"
          - "@eslint/*"
          - "@stylistic/*"
      dev-deps:
        patterns:
          - "sass"
          - "globals"
